name: CI - Build and Push Image

env:
  AWS_REGION: "eu-central-1"
  AWS_IAM_ROLE_ARN: "arn:aws:iam::655748577231:role/github-aws-integration-role"
  ECR_REPOSITORY: "predictive-llm-k8s-scaler"

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - restructure-k8s-envs
    paths:
      - "app/**"
      - ".github/workflows/ci-build.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}

      - name: Test AWS credentials
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image variables
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${SHORT_SHA}"

          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_URI \
            -f app/Dockerfile \
            app

      - name: Push Docker image to ECR
        run: docker push $IMAGE_URI

      - name: Create release info
        run: |
          mkdir -p release
          echo "IMAGE_URI=$IMAGE_URI" > release/release.env
          echo "IMAGE_TAG=$IMAGE_TAG" >> release/release.env
          echo "GIT_SHA=$GITHUB_SHA" >> release/release.env
          cat release/release.env

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-info
          path: release/release.env
