name: Destroy AWS Environment

env:
  AWS_REGION: "eu-central-1"
  AWS_IAM_ROLE_ARN: "arn:aws:iam::655748577231:role/github-aws-integration-role"
  EKS_CLUSTER_NAME: "predictive-llm-k8s-cluster"

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type DESTROY to confirm"
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment:
      name: aws-eks-dev

    steps:
      - name: Check confirmation
        run: |
          if [ "${{ inputs.confirm_destroy }}" != "DESTROY" ]; then
            echo "Destroy not confirmed. Type DESTROY to run this workflow."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}

      - name: Test AWS credentials
        run: aws sts get-caller-identity

      - name: Try update kubeconfig
        continue-on-error: true
        run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Cleanup Kubernetes resources
        continue-on-error: true
        run: |
          kubectl delete -f k8s/aws/predictive-llm-scaler.yaml --ignore-not-found
          kubectl delete -f k8s/aws/wiremock.yaml --ignore-not-found
          kubectl delete -f k8s/generated/scaler-configmap.yaml --ignore-not-found
          helm uninstall prometheus -n monitoring || true
          kubectl delete namespace monitoring --ignore-not-found || true
          kubectl get svc -A || true

      - name: Wait for cloud cleanup
        run: sleep 90

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
